### ISSUE TITLE
Concurrent access to HashSet<T> corrupts state

### ISSUE THREAD

**Issue by sharwell** [ni/csharp#50]
The following line is capable of triggering an infinite loop due to concurrent access of a `HashSet<T>` by multiple threads.

https://github.com/ni/csharp-styleguide/blob/ac073a252506f7500cd72c94f1b370ead607ed59/src/NationalInstruments.Analyzers/Style/SpellingAnalyzer.cs#L342

The access needs to be guarded (synchronized) and/or modified to avoid data sharing between concurrent analysis threads.

Originally reported at: https://developercommunity2.visualstudio.com/t/Visual-Studio-periodically-100-CPU-when/1282421

**Comment by Everest2020** [comment]
What about to add `.ToList()` at line 339?

**Comment by davkean** [comment]
Folks, I'm from the Visual Studio performance team and our performance telemetry has caught this issue in the wild. In the past 90 days, our CPU telemetry has caught it 4 times, at its worst was consuming 12 cores (!) all stuck in an infinite loop.
