### ISSUE TITLE
NI1800_ReadError errors when NI1800 is disabled

### ISSUE THREAD

**Issue by brianehenry** [ni/csharp#57]
I have NI1800 disabled in my ruleset, but I still get NI1800_ReadError errors for every project:

![image](https://user-images.githubusercontent.com/5454342/110837725-39544b00-8267-11eb-8a99-85363cc98d9a.png)

I'd expect that disabling NI1800 would also prevent NI1800_ReadError errors. 

I can work around this issue by explicitly disabling NI1800_ReadError in my ruleset like this:
`<Rule Id="NI1800_ReadError" Action="None" />`

@pakdev

**Comment by pakdev** [comment]
Thanks! Created a PR that should fix this
